#!/usr/bin/env python3

__all__ = (
    "Class",
)

"""
Class abstraction.
"""

import typing
from typing import Iterable, Optional, Tuple, Union

from ..types.reference import ClassOrInterfaceType

if typing.TYPE_CHECKING:
    from .field import Field
    from .method import Method
    from .._argument import FieldDescriptor, MethodDescriptor


class Class:
    """
    An abstract representation of a Java class.
    """

    # ------------------------------ Access flags ------------------------------ #

    @property
    def is_public(self) -> bool:
        """
        Is this class public (can be accessed outside the package)?
        """

        ...

    @is_public.setter
    def is_public(self, value: bool) -> None:
        ...

    @property
    def is_final(self) -> bool:
        """
        Is this class final (no subclasses allowed)?
        """

        ...

    @is_final.setter
    def is_final(self, value: bool) -> None:
        ...

    @property
    def is_super(self) -> bool:
        """
        Should superclass methods be treated specially by the invokespecial instruction?
        """

        ...

    @is_super.setter
    def is_super(self, value: bool) -> None:
        ...

    @property
    def is_interface(self) -> bool:
        """
        Is this class an interface?
        """

        ...

    @is_interface.setter
    def is_interface(self, value: bool) -> None:
        ...

    @property
    def is_abstract(self) -> bool:
        """
        Is this class abstract?
        """

        ...

    @is_abstract.setter
    def is_abstract(self, value: bool) -> None:
        ...

    @property
    def is_synthetic(self) -> bool:
        """
        Is this class synthetic (generated by the compiler)?
        """

        ...

    @is_synthetic.setter
    def is_synthetic(self, value: bool) -> None:
        ...

    @property
    def is_annotation(self) -> bool:
        """
        Is this class an annotation?
        """

        ...

    @is_annotation.setter
    def is_annotation(self, value: bool) -> None:
        ...

    @property
    def is_enum(self) -> bool:
        """
        Is this class an enum?
        """

        ...

    @is_enum.setter
    def is_enum(self, value: bool) -> None:
        ...

    @property
    def is_module(self) -> bool:
        """
        Is this class a module?
        """

        ...

    @is_module.setter
    def is_module(self, value: bool) -> None:
        ...

    # ------------------------------ Other properties ------------------------------ #

    @property
    def name(self) -> str:
        """
        The (internal) name of this class.
        """

        ...

    @name.setter
    def name(self, value: str) -> None:
        ...

    @property
    def super(self) -> Optional["Class"]:
        """
        The superclass of this class.
        """

        ...

    @super.setter
    def super(self, value: Optional["Class"]) -> None:
        ...

    @property
    def super_name(self) -> Optional[str]:
        """
        The name of the superclass of this class.
        """

        ...

    @super_name.setter
    def super_name(self, value: Optional[str]) -> None:
        ...

    @property
    def interfaces(self) -> Tuple["Class", ...]:
        """
        The interfaces that this class implements.
        """

        ...

    @interfaces.setter
    def interfaces(self, value: Iterable["Class"]) -> None:
        ...

    @property
    def interface_names(self) -> Tuple[str, ...]:
        """
        The names of the interfaces that this class implements.
        """

        ...

    @interface_names.setter
    def interface_names(self, value: Iterable[str]) -> None:
        ...

    @property
    def methods(self) -> Tuple["Method", ...]:
        """
        The methods inside this class.
        """

        ...

    @property
    def fields(self) -> Tuple["Field", ...]:
        """
        The fields inside this class.
        """

        ...

    # ------------------------------ Methods ------------------------------ #

    def get_method(self, name: str, *descriptor: "MethodDescriptor") -> "Method":
        """
        Gets a method in this class.

        :param name: The name of the method.
        :param descriptor: The descriptor of the method, if not given, the first method with the name is returned.
        :return: The method.
        """

        ...

    def add_method(self, name: str, *descriptor: "MethodDescriptor", **access_flags: bool) -> "Method":
        """
        Adds a method to this class given the provided information about it.

        :param name: The name of the method.
        :param descriptor: The descriptor of the method.
        :param access_flags: Any access flags to have on the method.
        :return: The method that was created.
        """

        ...

    def remove_method(self, name_or_method: Union[str, "Method"], *descriptor: "MethodDescriptor") -> "Method":
        """
        Removes a method from this class.

        :param name_or_method: The name of the method, or the method.
        :param descriptor: The descriptor of the method.
        :return: The method that was removed.
        """

        ...

    def get_field(self, name: str, descriptor: Optional["FieldDescriptor"] = None) -> "Field":
        """
        Gets a field in this class.

        :param name: The name of the field.
        :param descriptor: The descriptor of the field, if None, the first field with the name is returned.
        :return: The field.
        """

        ...

    def add_field(
            self, name: str, descriptor: Optional["FieldDescriptor"] = None, **access_flags: bool,
    ) -> "Field":
        """
        Adds a field to this class.

        :param name: The name of the field to add.
        :param descriptor: The descriptor of the field to add.
        :param access_flags: Any access flags to have on the field.
        :return: The field that was added.
        """

        ...

    def remove_field(self, name_or_field: Union[str, "Field"], descriptor: Optional["FieldDescriptor"] = None) -> "Field":
        """
        Removes a field from this class.

        :param name_or_field: The name of the field or the field.
        :param descriptor: The descriptor of the field.
        :return: The field that was removed.
        """

        ...

    def get_type(self) -> ClassOrInterfaceType:
        """
        :return: The type representation of this class.
        """

        return ClassOrInterfaceType(self.name)
