#!/usr/bin/env python3

__all__ = (
    "Method",
)

"""
Java method abstraction.
"""

import typing
from abc import abstractmethod, ABC
from typing import Tuple

from ..types import BaseType

if typing.TYPE_CHECKING:
    from .class_ import Class


class Method(ABC):
    """
    An abstract representation of a Java method.
    """

    # ------------------------------ Access flags ------------------------------ #

    @property
    @abstractmethod
    def is_public(self) -> bool:
        """
        :return: Is this method public?
        """

        ...

    @is_public.setter
    @abstractmethod
    def is_public(self, value: bool) -> None:
        ...

    @property
    @abstractmethod
    def is_private(self) -> bool:
        """
        :return: Is this method private?
        """

        ...

    @is_private.setter
    @abstractmethod
    def is_private(self, value: bool) -> None:
        ...

    @property
    @abstractmethod
    def is_protected(self) -> bool:
        """
        :return: Is this method protected?
        """

        ...

    @is_protected.setter
    @abstractmethod
    def is_protected(self, value: bool) -> None:
        ...

    @property
    @abstractmethod
    def is_static(self) -> bool:
        """
        :return: Is this method static?
        """

        ...

    @is_static.setter
    @abstractmethod
    def is_static(self, value: bool) -> None:
        ...

    @property
    @abstractmethod
    def is_final(self) -> bool:
        """
        :return: Is this method final (cannot be overriden)?
        """

        ...

    @is_final.setter
    @abstractmethod
    def is_final(self, value: bool) -> None:
        ...

    @property
    @abstractmethod
    def is_synchronized(self) -> bool:
        """
        :return: Is access to this method synchronized?
        """

        ...

    @is_synchronized.setter
    @abstractmethod
    def is_synchronized(self, value: bool) -> None:
        ...

    @property
    @abstractmethod
    def is_bridge(self) -> bool:
        """
        :return: Is this method generated by the compiler?
        """

        ...

    @is_bridge.setter
    @abstractmethod
    def is_bridge(self, value: bool) -> None:
        ...

    @property
    @abstractmethod
    def is_varargs(self) -> bool:
        """
        :return: Does this method have a variable number of arguments?
        """

        ...

    @is_varargs.setter
    @abstractmethod
    def is_varargs(self, value: bool) -> None:
        ...

    @property
    @abstractmethod
    def is_abstract(self) -> bool:
        """
        :return: Does this method have a provided implementation?
        """

        ...

    @is_abstract.setter
    @abstractmethod
    def is_abstract(self, value: bool) -> None:
        ...

    @property
    @abstractmethod
    def is_native(self) -> bool:
        """
        :return: Does this method reference a function defined in a native binary?
        """

        ...

    @is_native.setter
    @abstractmethod
    def is_native(self, value: bool) -> None:
        ...

    @property
    @abstractmethod
    def is_synthetic(self) -> bool:
        """
        :return: Is this method synthetic (generated by the compiler)?
        """

        ...

    @is_synthetic.setter
    @abstractmethod
    def is_synthetic(self, value: bool) -> None:
        ...

    # ------------------------------ Other properties ------------------------------ #

    @property
    @abstractmethod
    def name(self) -> str:
        """
        :return: The name of this method.
        """

        ...

    @name.setter
    @abstractmethod
    def name(self, value: bool) -> None:
        ...

    @property
    @abstractmethod
    def argument_types(self) -> Tuple[BaseType, ...]:
        """
        :return: The argument types of this method.
        """

        ...

    @argument_types.setter
    @abstractmethod
    def argument_types(self, value: Tuple[BaseType, ...]) -> None:
        ...

    @property
    @abstractmethod
    def return_type(self) -> BaseType:
        """
        :return: The return type of this method.
        """

        ...

    @return_type.setter
    @abstractmethod
    def return_type(self, value: BaseType) -> None:
        ...

    @property
    @abstractmethod
    def class_(self) -> "Class":
        """
        :return: The class that this method belongs to.
        """

        ...

    def get_reference(self) -> Tuple["Class", str, Tuple[BaseType, ...], BaseType]:
        """
        :return: A reference to this method that can be used in instructions.
        """

        return (self.class_, self.name, self.argument_types, self.return_type)

    def get_ref(self) -> Tuple["Class", str, Tuple[BaseType, ...], BaseType]:
        """
        :return: A reference to this method that can be used in instructions.
        """

        return (self.class_, self.name, self.argument_types, self.return_type)
